"""
So that your posts don't come across AS spammy the program will randomly select a canned message from this list. At the moment the fields CITY and TITLE can be used anywhere in the message. To add more variables they need referenced from the job JSON object passed to the calling method, search for this line in the main program:

msg = hs.create_message(job, messages.MESSAGES)

Whatever is in the job JSON object is usable.

Notes:

$ = converts the title value to plural with the english module.
"""

MESSAGES = [
	"{city} area IT job seekers, Dollar Bank is looking for a wicked talented {title} to join our team! Interested? Follow this link to apply. Referral mentions greatly appreciated! Also, did you know? This post was generated by a python script? Check my GitHub (https://github.com/jtroussard/linkedin_assist/) account for more details.",
	"$Calling {city} area {title}. Dollar Bank is hiring! Interested? Follow this link. Referral mentions greatly appreciated. Also, did you know this post was automatically shared by a program? Check out my GitHub repo to learn more. (https://github.com/jtroussard/linkedin_assist/)",
	"$Attention all {city} area {title}. Dollar Bank is hiring! Interested? Follow this link. Referral mentions greatly appreciated. Also, did you know this post was automatically shared by a program? Check out my GitHub repo to learn more. (https://github.com/jtroussard/linkedin_assist/)",
	"Do you have experience as a {title}? Dollar Bank is looking for talented individuals to join our team. Follow the main link for more details. Referral mentions greatly appreciated. Also did you know this post share was automated using LinkedIn\'s API and some python code? Code is available on my GitHub account(https://github.com/jtroussard/linkedin_assist/).",
	"Dollar Bank in {city}, is currently looking for a highly qualified {title}. If you're looking for a great work environment, good benefits, and even better co-workers this might be the position for you. Follow the main link for more details. Referral mentions greatly appreciated. Also it might not seem like it but this post was made without me having to log into LinkedIn! Wanna know how? Check out my GitHut Repo for all the magic. (https://github.com/jtroussard/linkedin_assist)"
	]